name: Publish NPM package (pre-release)
on:
  push:
    tags:
      - 'v[0-9].[0-9]+.[0-9]+-*.[0-9]+'

env:
  TAG: $(git describe --tags --abbrev=0)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@digando'
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
      - run: npm run build
      # Publish package with committed package version in package.json
      - run: npm publish --tag beta
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
